### ISSUE TITLE
青龙怎么使用

### ISSUE THREAD

**Issue by a1564471347** [arlettebrook/tencentVideoSign-in#1]
这些脚本

**Comment by arlettebrook** [comment]
[青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用

**Comment by a1564471347** [comment]
> [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用



> [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用

是不是拉取整个库，然后cookie填入cfg文件里面运行对应脚本即可

**Comment by arlettebrook** [comment]
> > [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用
> 
> 
> 
> > [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用
> 
> 是不是拉取整个库，然后cookie填入cfg文件里面运行对应脚本即可

还要安装依赖，不会用这个[autoCheck-in](https://github.com/Arlettebrook/autoCheck-in)，只需要配置Secrets，就能每天运行

**Comment by a1564471347** [comment]
> > > [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用
> > 
> > 
> > > [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用
> > 
> > 
> > 是不是拉取整个库，然后cookie填入cfg文件里面运行对应脚本即可
> 
> 还要安装依赖，不会用这个[autoCheck-in](https://github.com/Arlettebrook/autoCheck-in)，只需要配置Secrets，就能每天运行

readme加个青龙教程吧还是习惯用青龙

**Comment by a1564471347** [comment]
> > > [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用
> > 
> > 
> > > [青龙](https://github.com/whyour/qinglong)怎么使用，这些Python脚本就怎么使用
> > 
> > 
> > 是不是拉取整个库，然后cookie填入cfg文件里面运行对应脚本即可
> 
> 还要安装依赖，不会用这个[autoCheck-in](https://github.com/Arlettebrook/autoCheck-in)，只需要配置Secrets，就能每天运行

aqiyi可以加上三次摇一摇和v6以上的抽白金任务吗

**Comment by arlettebrook** [comment]
> aqiyi可以加上三次摇一摇和v6以上的抽白金任务吗

没有账号测试，可以去搜一下别的仓库，有的话自己加进去
